// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models';

export class Service {
	/**
	 * Get myfile languages
	 * @returns Language Default response body
	 * @throws ApiError
	 */
	public static getLanguages(data: $OpenApiTs['/languages']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/languages']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/languages',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Add case files
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static addCaseFiles(data: $OpenApiTs['/cases/{caseId}/files']['post']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}/files']['post']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/cases/{caseId}/files',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete case files
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static deleteCaseFiles(data: $OpenApiTs['/cases/{caseId}/files']['delete']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}/files']['delete']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/cases/{caseId}/files',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get case files
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static getCaseFileListing(data: $OpenApiTs['/cases/{caseId}/files']['get']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}/files']['get']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/cases/{caseId}/files',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update case file
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static updateCaseFile(data: $OpenApiTs['/cases/files/{id}']['patch']['req']): CancelablePromise<$OpenApiTs['/cases/files/{id}']['patch']['res'][200]> {
		const {
                    id,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/cases/files/{id}',
			path: {
				id
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user files.
	 * @returns GetUserFilesResponse Default response body
	 * @throws ApiError
	 */
	public static getUserFiles(data: $OpenApiTs['/users/{userId}/files']['get']['req']): CancelablePromise<$OpenApiTs['/users/{userId}/files']['get']['res'][200]> {
		const {
                    userId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/{userId}/files',
			path: {
				userId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Create user file.
	 * @returns CreateUserFileRequest Default response body
	 * @throws ApiError
	 */
	public static createUserFile(data: $OpenApiTs['/users/files']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/users/files']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/users/files',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update user file.
	 * @returns UpdateFamilyMemberResponse Default response body
	 * @throws ApiError
	 */
	public static updateUserFile(data: $OpenApiTs['/users/files']['patch']['req'] = {}): CancelablePromise<$OpenApiTs['/users/files']['patch']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/users/files',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete user file.
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static deleteUserFile(data: $OpenApiTs['/users/files']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/users/files']['delete']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/users/files',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user family member files.
	 * @returns GetUserFilesResponse Default response body
	 * @throws ApiError
	 */
	public static getUserFamilyMemberFiles(data: $OpenApiTs['/users/{userId}/files/family-member']['get']['req']): CancelablePromise<$OpenApiTs['/users/{userId}/files/family-member']['get']['res'][200]> {
		const {
                    userId,
userFamilyMemberId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/{userId}/files/family-member',
			path: {
				userId
			},
			query: {
				userFamilyMemberId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get download url for user file.
	 * @returns UserFileDownloadResponse Default response body
	 * @throws ApiError
	 */
	public static getUserFileDownloadUrl(data: $OpenApiTs['/users/files/download']['get']['req']): CancelablePromise<$OpenApiTs['/users/files/download']['get']['res'][200]> {
		const {
                    fileId,
uploadVersionId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/files/download',
			query: {
				fileId, uploadVersionId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get cases for user file.
	 * @returns GetUserFileCasesResponse Default response body
	 * @throws ApiError
	 */
	public static getUserFileCases(data: $OpenApiTs['/users/files/{fileId}/cases']['get']['req']): CancelablePromise<$OpenApiTs['/users/files/{fileId}/cases']['get']['res'][200]> {
		const {
                    fileId,
userId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/files/{fileId}/cases',
			path: {
				fileId, userId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update generated file
	 * @returns UpdateGeneratedFileResponse Default response body
	 * @throws ApiError
	 */
	public static updateGeneratedFile(data: $OpenApiTs['/users/files/generated']['patch']['req'] = {}): CancelablePromise<$OpenApiTs['/users/files/generated']['patch']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/users/files/generated',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get generated file download url
	 * @returns UserFileDownloadResponse Default response body
	 * @throws ApiError
	 */
	public static getGeneratedFileDownloadUrl(data: $OpenApiTs['/users/files/generated/download']['get']['req']): CancelablePromise<$OpenApiTs['/users/files/generated/download']['get']['res'][200]> {
		const {
                    generatedFileId,
userId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/files/generated/download',
			query: {
				generatedFileId, userId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Add user workflow
	 * @returns AddWorkFlowResponse Default response body
	 * @throws ApiError
	 */
	public static addUserWorkflow(data: $OpenApiTs['/users/workflows']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/users/workflows']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/users/workflows',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Remove user workflow
	 * @returns DeleteWorkFlowResponse Default response body
	 * @throws ApiError
	 */
	public static removeUserWorkflow(data: $OpenApiTs['/users/workflows']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/users/workflows']['delete']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/users/workflows',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user workflows
	 * @returns GetUserWorkFlowsResponse Default response body
	 * @throws ApiError
	 */
	public static getUserWorkflows(data: $OpenApiTs['/users/workflows']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/users/workflows']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/workflows',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get myfile workflows
	 * @returns Workflow Default response body
	 * @throws ApiError
	 */
	public static getWorkflows(data: $OpenApiTs['/workflows']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/workflows']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/workflows',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Create a user family member
	 * @returns CreateFamilyMemberResponse Default response body
	 * @throws ApiError
	 */
	public static createUserFamilyMember(data: $OpenApiTs['/user/family']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/user/family']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/user/family',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update user family member
	 * @returns UpdateFamilyMemberResponse Default response body
	 * @throws ApiError
	 */
	public static updateUserFamilyMember(data: $OpenApiTs['/user/family']['patch']['req'] = {}): CancelablePromise<$OpenApiTs['/user/family']['patch']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/user/family',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete user family members
	 * @returns DeleteFamilyMemberResponse Default response body
	 * @throws ApiError
	 */
	public static deleteFamilyMember(data: $OpenApiTs['/user/family']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/user/family']['delete']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/user/family',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user family members
	 * @returns FamilyMember Default response body
	 * @throws ApiError
	 */
	public static getFamilyMembers(data: $OpenApiTs['/user/family']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/user/family']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/user/family',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user family member
	 * @returns FamilyMember Default response body
	 * @throws ApiError
	 */
	public static getFamilyMember(data: $OpenApiTs['/user/family/{id}']['get']['req']): CancelablePromise<$OpenApiTs['/user/family/{id}']['get']['res'][200]> {
		const {
                    id,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/user/family/{id}',
			path: {
				id
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Add case family members
	 * @returns AddCaseApplicantsResponse Default response body
	 * @throws ApiError
	 */
	public static addCaseFamilyMembers(data: $OpenApiTs['/case/{caseId}/family-members']['post']['req']): CancelablePromise<$OpenApiTs['/case/{caseId}/family-members']['post']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/case/{caseId}/family-members',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete case family members
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static deleteCaseFamilyMembers(data: $OpenApiTs['/case/{caseId}/family-members']['delete']['req']): CancelablePromise<$OpenApiTs['/case/{caseId}/family-members']['delete']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/case/{caseId}/family-members',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get case family members
	 * @returns CaseApplicant Default response body
	 * @throws ApiError
	 */
	public static getCaseFamilyMembers(data: $OpenApiTs['/case/{caseId}/family-members']['get']['req']): CancelablePromise<$OpenApiTs['/case/{caseId}/family-members']['get']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/case/{caseId}/family-members',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Create a new case
	 * @returns CreateCaseResponse Default response body
	 * @throws ApiError
	 */
	public static createCase(data: $OpenApiTs['/cases']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/cases']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/cases',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user cases
	 * @returns getCaseResponse Default response body
	 * @throws ApiError
	 */
	public static getCases(data: $OpenApiTs['/cases']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/cases']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/cases',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update a case
	 * @returns UpdateCaseResponse Default response body
	 * @throws ApiError
	 */
	public static updateCase(data: $OpenApiTs['/cases/{caseId}']['patch']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}']['patch']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/cases/{caseId}',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete a case
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static deleteCase(data: $OpenApiTs['/cases/{caseId}']['delete']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}']['delete']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/cases/{caseId}',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get a single case
	 * @returns GetCaseResponse Default response body
	 * @throws ApiError
	 */
	public static getCase(data: $OpenApiTs['/cases/{caseId}']['get']['req']): CancelablePromise<$OpenApiTs['/cases/{caseId}']['get']['res'][200]> {
		const {
                    caseId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/cases/{caseId}',
			path: {
				caseId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Create user.
	 * @returns CreateUserResponse Default response body
	 * @throws ApiError
	 */
	public static createUser(data: $OpenApiTs['/users']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/users']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/users',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get NYCID user data
	 * @returns User Default response body
	 * @throws ApiError
	 */
	public static getUser(data: $OpenApiTs['/users']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/users']['get']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Update user.
	 * @returns UpdateUserResponse Default response body
	 * @throws ApiError
	 */
	public static updateUser(data: $OpenApiTs['/users']['patch']['req'] = {}): CancelablePromise<$OpenApiTs['/users']['patch']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'PATCH',
			url: '/users',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Delete user
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static deleteUser(data: $OpenApiTs['/users']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/users']['delete']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/users',
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Get user activity.
	 * @returns GetUserActivityResponse Default response body
	 * @throws ApiError
	 */
	public static getUserActivity(data: $OpenApiTs['/users/activities']['get']['req']): CancelablePromise<$OpenApiTs['/users/activities']['get']['res'][200]> {
		const {
                    filters,
page,
limit,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'GET',
			url: '/users/activities',
			query: {
				filters, page, limit
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

	/**
	 * Post message to connections
	 * @returns any Default response body
	 * @throws ApiError
	 */
	public static postMessagingPostMessageToWsConnections(data: $OpenApiTs['/messaging/post-message-to-ws-connections']['post']['req']): CancelablePromise<$OpenApiTs['/messaging/post-message-to-ws-connections']['post']['res'][200]> {
		const {
                    userId,
requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/messaging/post-message-to-ws-connections',
			path: {
				userId
			},
			body: requestBody,
			mediaType: 'application/json',
		});
	}

}