/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CaseApplicant
 */
export interface CaseApplicant {
    /**
     * 
     * @type {string}
     * @memberof CaseApplicant
     */
    CaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseApplicant
     */
    UserFamilyMemberId?: string;
    /**
     * 
     * @type {any}
     * @memberof CaseApplicant
     */
    UserFamilyMember?: any;
    /**
     * 
     * @type {any}
     * @memberof CaseApplicant
     */
    _Case?: any;
}
