/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CaseCriterion
 */
export interface CaseCriterion {
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    Status?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    LastModifiedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    CaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    UserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    WorkflowStageCriterionId?: string;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    LastModifiedByUser?: any;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    _Case?: any;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    WorkflowStageCriterion?: any;
}
