/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface CaseNote
 */
export interface CaseNote {
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    noteText?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    parentNoteId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    authorUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    noteAudienceScope?: string;
    /**
     * 
     * @type {User}
     * @memberof CaseNote
     */
    authorUser?: User;
    /**
     * 
     * @type {string}
     * @memberof CaseNote
     */
    caseId?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof CaseNote
     */
    caseNoteReplies?: Array<any>;
    /**
     * 
     * @type {any}
     * @memberof CaseNote
     */
    caseNote?: any;
}
