/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CaseCriterion
 */
export interface CaseCriterion {
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    lastModifiedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    caseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CaseCriterion
     */
    workflowStageCriterionId?: string;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    lastModifiedByUser?: any;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    _case?: any;
    /**
     * 
     * @type {any}
     * @memberof CaseCriterion
     */
    workflowStageCriterion?: any;
}
