/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    FirstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    LastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    Email: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserRequest
     */
    DOB: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    LanguageId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateUserRequest
     */
    Workflows?: Array<string>;
}
