/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseAttributes } from './case-attributes';
/**
 * 
 * @export
 * @interface CreateCaseRequestBody
 */
export interface CreateCaseRequestBody {
    /**
     * 
     * @type {string}
     * @memberof CreateCaseRequestBody
     */
    CaseTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCaseRequestBody
     */
    CaseType: string;
    /**
     * 
     * @type {CaseAttributes}
     * @memberof CreateCaseRequestBody
     */
    CaseAttributes?: CaseAttributes;
    /**
     * 
     * @type {string}
     * @memberof CreateCaseRequestBody
     */
    CaseIdentifier: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCaseRequestBody
     */
    FamilyMemberIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateCaseRequestBody
     */
    WorkflowId: string;
}
