/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserFileRequestFiles
 */
export interface CreateUserFileRequestFiles {
    /**
     * 
     * @type {string}
     * @memberof CreateUserFileRequestFiles
     */
    ContentType: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserFileRequestFiles
     */
    OriginalFilename: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUserFileRequestFiles
     */
    SizeInBytes: number;
    /**
     * 
     * @type {number}
     * @memberof CreateUserFileRequestFiles
     */
    PageNumber: number;
}
