/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateUserFileRequestFiles } from './create-user-file-request-files';
/**
 * 
 * @export
 * @interface CreateUserFileRequest
 */
export interface CreateUserFileRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserFileRequest
     */
    userFamilyMemberId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserFileRequest
     */
    title: string;
    /**
     * 
     * @type {Array<CreateUserFileRequestFiles>}
     * @memberof CreateUserFileRequest
     */
    files: Array<CreateUserFileRequestFiles>;
}
