/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseApplicant } from './case-applicant';
import { CaseAttributes } from './case-attributes';
import { CaseCriterion } from './case-criterion';
import { CaseFile } from './case-file';
import { CaseNote } from './case-note';
import { CaseTeamAssignment } from './case-team-assignment';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    caseType?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    percentComplete?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    agencyCaseIdentifier?: string;
    /**
     * 
     * @type {CaseAttributes}
     * @memberof InlineResponse200
     */
    caseAttributes?: CaseAttributes;
    /**
     * 
     * @type {Array<CaseCriterion>}
     * @memberof InlineResponse200
     */
    caseCriteria?: Array<CaseCriterion>;
    /**
     * 
     * @type {Array<CaseNote>}
     * @memberof InlineResponse200
     */
    caseNotes?: Array<CaseNote>;
    /**
     * 
     * @type {Array<CaseTeamAssignment>}
     * @memberof InlineResponse200
     */
    caseTeamAssignments?: Array<CaseTeamAssignment>;
    /**
     * 
     * @type {Array<CaseFile>}
     * @memberof InlineResponse200
     */
    caseFiles?: Array<CaseFile>;
    /**
     * 
     * @type {Array<CaseApplicant>}
     * @memberof InlineResponse200
     */
    caseApplicants?: Array<CaseApplicant>;
}
