/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Language
 */
export interface Language {
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    Name: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    Code: string;
    /**
     * 
     * @type {Date}
     * @memberof Language
     */
    CreatedAt: Date;
}
