/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseApplicant } from './case-applicant';
import { CaseAttributes } from './case-attributes';
import { CaseCriterion } from './case-criterion';
import { CaseFile } from './case-file';
import { CaseNote } from './case-note';
import { CaseTeamAssignment } from './case-team-assignment';
/**
 * 
 * @export
 * @interface ModelCase
 */
export interface ModelCase {
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    Title?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    CaseType?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelCase
     */
    PercentComplete?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    AgencyCaseIdentifier?: string;
    /**
     * 
     * @type {CaseAttributes}
     * @memberof ModelCase
     */
    CaseAttributes?: CaseAttributes;
    /**
     * 
     * @type {Array<CaseCriterion>}
     * @memberof ModelCase
     */
    CaseCriteria?: Array<CaseCriterion>;
    /**
     * 
     * @type {Array<CaseNote>}
     * @memberof ModelCase
     */
    CaseNotes?: Array<CaseNote>;
    /**
     * 
     * @type {Array<CaseTeamAssignment>}
     * @memberof ModelCase
     */
    CaseTeamAssignments?: Array<CaseTeamAssignment>;
    /**
     * 
     * @type {Array<CaseFile>}
     * @memberof ModelCase
     */
    CaseFiles?: Array<CaseFile>;
    /**
     * 
     * @type {Array<CaseApplicant>}
     * @memberof ModelCase
     */
    CaseApplicants?: Array<CaseApplicant>;
}
