/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlatformActivityLogs
 */
export interface PlatformActivityLogs {
    /**
     * 
     * @type {string}
     * @memberof PlatformActivityLogs
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformActivityLogs
     */
    activityType?: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformActivityLogs
     */
    activityValue?: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformActivityLogs
     */
    relatedId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlatformActivityLogs
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PlatformActivityLogs
     */
    activityGeneratedByUserId?: string;
    /**
     * 
     * @type {any}
     * @memberof PlatformActivityLogs
     */
    metadata?: any;
    /**
     * 
     * @type {any}
     * @memberof PlatformActivityLogs
     */
    user?: any;
}
