/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserRequest
     */
    DOB?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    languageId?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserRequest
     */
    tOSAcceptedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserRequest
     */
    pPAcceptedAt?: Date;
}
