/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateGeneratedFileResponse
 */
export interface UpdateGeneratedFileResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileResponse
     */
    ContentType?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileResponse
     */
    OriginalFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileResponse
     */
    Status?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateGeneratedFileResponse
     */
    SizeInBytes?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateGeneratedFileResponse
     */
    CreatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateGeneratedFileResponse
     */
    LastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileResponse
     */
    Title?: string;
}
