/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateFamilyMemberRequest
 */
export interface UpdateFamilyMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberRequest
     */
    FirstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberRequest
     */
    LastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateFamilyMemberRequest
     */
    Dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberRequest
     */
    Relationship?: string;
}
