/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseApplicant } from './case-applicant';
import { User } from './user';
import { UserFile } from './user-file';
/**
 * 
 * @export
 * @interface UpdateFamilyMemberResponse
 */
export interface UpdateFamilyMemberResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberResponse
     */
    FirstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberResponse
     */
    LastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberResponse
     */
    UserId?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateFamilyMemberResponse
     */
    DOB?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateFamilyMemberResponse
     */
    Relationship?: string;
    /**
     * 
     * @type {User}
     * @memberof UpdateFamilyMemberResponse
     */
    User?: User;
    /**
     * 
     * @type {Array<CaseApplicant>}
     * @memberof UpdateFamilyMemberResponse
     */
    CaseApplicants?: Array<CaseApplicant>;
    /**
     * 
     * @type {Array<UserFile>}
     * @memberof UpdateFamilyMemberResponse
     */
    UserFiles?: Array<UserFile>;
}
