/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseAttributes } from './case-attributes';
/**
 * 
 * @export
 * @interface UpdateCaseRequestBody
 */
export interface UpdateCaseRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    caseTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    caseType?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateCaseRequestBody
     */
    percentComplete?: number;
    /**
     * 
     * @type {CaseAttributes}
     * @memberof UpdateCaseRequestBody
     */
    caseAttributes?: CaseAttributes;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    agencyCaseIdentifier?: string;
}
