/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseAttributes } from './case-attributes';
/**
 * 
 * @export
 * @interface UpdateCaseRequestBody
 */
export interface UpdateCaseRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    CaseTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    CaseType?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateCaseRequestBody
     */
    PercentComplete?: number;
    /**
     * 
     * @type {CaseAttributes}
     * @memberof UpdateCaseRequestBody
     */
    CaseAttributes?: CaseAttributes;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    Status?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCaseRequestBody
     */
    AgencyCaseIdentifier?: string;
}
