/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateUserFamilyRequest
 */
export interface UpdateUserFamilyRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserFamilyRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserFamilyRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserFamilyRequest
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserFamilyRequest
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserFamilyRequest
     */
    relationship?: string;
}
