/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateGeneratedFileRequest
 */
export interface UpdateGeneratedFileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileRequest
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileRequest
     */
    originalFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileRequest
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateGeneratedFileRequest
     */
    sizeInBytes?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateGeneratedFileRequest
     */
    title?: string;
}
