/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    FirstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    LastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    Email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    LegacyId?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    IdpId?: string;
}
