/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserFile
 */
export interface UserFile {
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    LegacyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    ContentType: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    ActiveVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    OriginalFilename: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    Title: string;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    CreatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    LastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    OwnerUserId?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof UserFile
     */
    UploadedMediaAssetVersions?: Array<any>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserFile
     */
    UploadUrls?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    CreatedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    LastModifiedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    UploadUrl?: string;
}
