/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserFile
 */
export interface UserFile {
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    legacyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    activeVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    originalFilename: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    ownerUserId?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof UserFile
     */
    uploadedMediaAssetVersions?: Array<any>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserFile
     */
    uploadUrls?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    createdByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    lastModifiedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    uploadUrl?: string;
}
