/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseApplicant } from './case-applicant';
import { User } from './user';
import { UserFile } from './user-file';
/**
 * 
 * @export
 * @interface UserFamily
 */
export interface UserFamily {
    /**
     * 
     * @type {string}
     * @memberof UserFamily
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserFamily
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFamily
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFamily
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserFamily
     */
    DOB?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserFamily
     */
    relationship?: string;
    /**
     * 
     * @type {User}
     * @memberof UserFamily
     */
    user?: User;
    /**
     * 
     * @type {Array<CaseApplicant>}
     * @memberof UserFamily
     */
    caseApllicants?: Array<CaseApplicant>;
    /**
     * 
     * @type {Array<UserFile>}
     * @memberof UserFamily
     */
    userFiles?: Array<UserFile>;
}
