/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WorkflowStageCriterion
 */
export interface WorkflowStageCriterion {
    /**
     * 
     * @type {string}
     * @memberof WorkflowStageCriterion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStageCriterion
     */
    CaseWorkflowStageId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStageCriterion
     */
    Name?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof WorkflowStageCriterion
     */
    CaseCriteria?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStageCriterion
     */
    CriterionFulfillmentType?: string;
    /**
     * 
     * @type {any}
     * @memberof WorkflowStageCriterion
     */
    WorkflowStage?: any;
}
