/* tslint:disable */
/* eslint-disable */
/**
 * My File NYC
 * This api represents a combination of all API Gateway Lambda Proxy components for My File NYC.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wereid@nycopportunity.nyc.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkflowStage } from './workflow-stage';
/**
 * 
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    id: string;
    /**
     * 
     * @type {Array<WorkflowStage>}
     * @memberof Workflow
     */
    WorkflowStages?: Array<WorkflowStage>;
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    Name?: string;
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    Description?: string;
}
